export const STUDENTS_REQUEST = "STUDENTS_REQUEST";
export const STUDENTS_SUCCESS = "STUDENTS_SUCCESS";
export const STUDENTS_FAIL = "STUDENTS_FAIL";

export const STUDENT_REQUEST = "STUDENT_REQUEST";
export const STUDENT_SUCCESS = "STUDENT_SUCCESS";
export const STUDENT_FAIL = "STUDENT_FAIL";
