export const TEACHERS_REQUEST = "TEACHERS_REQUEST";
export const TEACHERS_SUCCESS = "TEACHERS_SUCCESS";
export const TEACHERS_FAIL = "TEACHERS_FAIL";

export const TEACHER_REQUEST = "TEACHER_REQUEST";
export const TEACHER_SUCCESS = "TEACHER_SUCCESS";
export const TEACHER_FAIL = "TEACHER_FAIL";
